### ISSUE TITLE
Sending Alt-Enter does not work

### ISSUE THREAD

**Issue by chrismgray** [rpwoodbu/mosh-chrome#109]
I use emacs org-mode and Alt-Enter (and Shift-Alt-Enter) are fairly important key chords.  Neither works in the chrome app.

**Comment by rpwoodbu** [comment]
I believe I am able to repro this. Best I can tell, this is a problem with both Mosh for Chrome and Secure Shell (which both use hterm as their terminal emulators), and it affects both Chrome OS and Linux (Ubuntu w/Cinnamon). However, I do seem to be able to send Alt-Enter via Chrome Remote Desktop, so it _is_ possible to capture that key. I don't have any program that I know uses Alt-Enter, so it is hard for me to test that the right code is being sent (and I don't know Emacs).

I'm betting this is an hterm thing, but maybe it is a Chrome App thing. I'll leave this bug here, but if you go bother the Secure Shell folks, they're more likely to find a solution. Once they have one, I can copy their efforts.

**Comment by vapier** [comment]
the [default hterm keyboard map](https://chromium.googlesource.com/apps/libapps/+/hterm-1.74/hterm/js/hterm_keyboard_keymap.js#273) has:
```js
this.addKeyDefs(
  | // These fields are: [keycode, keycap, normal, control, alt, meta]
  [13,  '[ENTER]', '\r',    CANCEL,                         CANCEL,  DEFAULT],
```

that means `Ctrl-Enter` and `Alt-Enter` are swallowed.  but you can override them with your [keyboard bindings](https://chromium.googlesource.com/apps/libapps/+/hterm-1.74/hterm/doc/KeyboardBindings.md).

do you have any reference for emacs and what it expects ?  doesn't seem to me like there's an agreed upon behavior here for these keypresses, so i find it hard to believe it's critical to emacs functionality.

| terminal | Ctrl-Enter | Alt-Enter | Shift-Alt-Enter |
|-|-|-|-|
| xterm | ^M | fullscreen window | fullscreen window |
| konsole | ^M | \e^M | \e\eOM^M |
| yakuake | ^M | \e^M | \e\eOM^M |
| gnome/vte | ^M | \e^M | \e^M |
| rxvt/urxvt | ^M | \e^M | \e^M |
| Eterm | ^M | \e^M | \e^M |
| st | ^M | \e^M | ^M |
| hterm | ignore | ignore | ignore |

to be clear, `^M` is the same as hitting `Enter` which is the same as `Ctrl-M`.

**Comment by chrismgray** [comment]
This is not a mosh issue, but an hterm issue, and can be fixed there.  The org-mode package for emacs does make extensive use of the Alt-Enter and Shift-Alt-Enter keybindings for creating new notes, but since the bug doesn't really apply here, I will close it rather than explaining how.

**Comment by vapier** [comment]
so you're going to file a bug using https://goo.gl/vb94JY ?

**Comment by chrismgray** [comment]
I sent https://chromium-review.googlesource.com/c/apps/libapps/+/508475 which was rejected.

**Comment by vapier** [comment]
that's a bit misleading.  here's what i actually said:

> > What is the rationale for not sending anything by default when the user holds down Alt and hits the Enter key?
> 
> no idea.  this is where you'd want to go through the file history in git to track things down.
> 
> in general, if you have questions or need help, we have chromium-hterm@chromium.org group where people post.
> 
> so i think we can drop this CL ? :)  i dislike adding new preferences (we've got a lot already), and we can debate the default alt+enter behavior in the mailing list.

you never started the thread on the mailing list for wider discussion, or did the requested history analysis.

**Comment by chrismgray** [comment]
Ah, sorry I didn't realize you were the same person.  I solved the problem using the method you suggested, and didn't feel like starting the thread or doing the history analysis.  I didn't mean to put words in your mouth.

**Comment by vapier** [comment]
np.  i'm happy to discuss changing the defaults, i just want to do it in a place where others can chime in and with a bit of background before we do.  people get very upset when you change keyboard defaults in a way they dislike :/.

also, that CL was about adding a pref rather than just changing the default keymap.  so i'd still decline a dedicated pref rather than changing the keymap.

**Comment by chrismgray** [comment]
No worries.  I don't feel the need to be part of changing the default -- I've got my preference set now and I'm sure I'm in a small minority intersection of hterm users and emacs org-mode users.  :)

**Comment by eshagh** [comment]
@chrismgray I think I'm after the same thing you are. Would you mind posting your full preferences? The alt-enter preference

`{
  "Alt-ENTER": "'\u001b\r'"
}`

works for alt+enter, but I'm about to go about figuring out shift+alt+enter as well as ctrl+arrow keys for re-positioning items, and I'm sure there are other hidden surprises in store for me. If you happen to have sorted out the preferences file for org mode in hterm, you'd be giving me a head start. :)
