### ISSUE TITLE
send-encoding setting sticks to "raw"

### ISSUE THREAD

**Issue by jdehaan** [rpwoodbu/mosh-chrome#135]
The option "send-encoding" sticks to "raw" and this avoids being able to send a simple "§" character to the console. It appears as question mark because probably a send/receive mismatch.

Directly using the ssh extension in send and receive utf-8 works fine. So I suppose the setting for "send-encoding" is lost on the way similarly maybe to how the AtlGr issue (#133) did.

PS: sorry for keeping triggering work regarding these annoying things ;-)

**Comment by rpwoodbu** [comment]
It would appear that, a long time ago (in SHA 1143dc021365fd13b7d9bcbbeca2e6122fcb6d1d), I forced this to "raw" to fix Unicode input. But now it seems that this actually _breaks_ it. I'll roll this back and build a new release candidate tonight.

**Comment by rpwoodbu** [comment]
Also FTR, this was "fixed" in Issue #2, but that still doesn't explain why that helped. I'm assuming that hterm has changed behavior in the interim.

**Comment by rpwoodbu** [comment]
OK, try v0.4.4 dev release. Thanks for finding these issues!

**Comment by rpwoodbu** [comment]
Oh, I should point out that this fix will _not_ revert `send-encoding` from `raw` to `utf-8` automatically. It will, however, be set to `utf-8` by default for new users. Existing users will need to revert this setting themselves, perhaps by hitting the "Reset to defaults" button in the preferences editor.

The reason is that it isn't possible to know whether this was set to `raw` by the user or by the old code, or whether the user is enjoying the `raw` mode and would be broken by forcing it to `utf-8`. I considered heuristics, but they are just that, and I'd rather not surprise users. I'll add an entry to the FAQ about Unicode input.

**Comment by jdehaan** [comment]
I think your decision for handling the parameter is smart and less annoying for users who were happy with the previous state.

For me it works like a charm now and I think I can start using mosh more intensively! Many thanks
