### ISSUE TITLE
tmux 2.1 copy doesn't work anymore

### ISSUE THREAD

**Issue by jgallen23** [rpwoodbu/mosh-chrome#138]
Just updated tmux to 2.1 and I've lost the ability to copy selection to clipboard.  I did a bit of research and it looks like I need to `copy-pipe` into a process that sets the clipboard (pbcopy, xclip).  Is that possible?

**Comment by rpwoodbu** [comment]
If I understand what you're asking, you want the terminal emulator (hterm) in Mosh for Chrome to call out to an external binary to set the clipboard. That's never going to work with a Chrome App. However, hterm does know how to address the local clipboard through the Chrome APIs, so I'm surprised this has stopped working. I use tmux, but I haven't gotten to 2.1 yet.

It would help to narrow down the issue here. If you make an ordinary ssh connection from a battle-hardened terminal emulator (e.g., xterm), does this work correctly for you? If so, try using the Secure Shell app, which uses the same hterm terminal emulator. If that works, try making a Mosh connection with the native `mosh` command from within a local xterm. If any of these fail, we'll know better where to look. If they don't, then we'll have to start comparing mosh and hterm versions.

**Comment by rpwoodbu** [comment]
I just updated the dev channel to hterm 1.61, which might fix your issue. According to the [changelog](https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/doc/ChangeLog.md), this happened in hterm 1.58 (a version later than the one in the stable channel):

> In hterm_terminal.js, use Terminal.prototype.copySelectionToClipboard, rather than the raw hterm.copySelectionToClipboard.

If you want to test it out, install "Mosh (dev)" and give it a go.

**Comment by burcin** [comment]
After seeing that the dev version (1.5.0) still didn't work, I decided to look elsewhere for the problem. Lo and behold, updating mosh on the server side (from 1.2.4a to 1.3.0 in this case) solved the issue. Both dev and stable versions work as expected, so I suggest closing this ticket.
