### ISSUE TITLE
Support for multiple SSH keys/certs

### ISSUE THREAD

**Issue by oskar456** [rpwoodbu/mosh-chrome#147]
For a few servers, I use OpenSSH certificate for authentication. That means I use not only private key file `id-rsa` but also certificate file `id-rsa-cert.pub`. It works very well with OpenSSH or with Chrome SSH app. But for Mosh app, there is no way how to add the private key and the certificate at the same time.

It would be nice if there were such option, as well as option to have more than one identity or custom SSH config file. Ideally in a similar way it works in the Secure Shell Chrome app.

**Comment by rpwoodbu** [comment]
I do know that Mosh for Chrome supports SSH certificates. So the issue here is how to have more than one credential at a time. This shouldn't be too hard to do; the keys/certs are in PEM format, which is well-delineated. I should be able to permit adding multiple keys/certs, and the code can go through them all to find one suitable for the remote server (similar to how OpenSSH works).

It would definitely be better to have multiple identities like the Secure Shell app, as you say. Having a way to manage connection profiles has been on my to-do list (Issue #29) since the beginning, but it is just enough UI work that I've never bothered (nor has anyone stepped up to contribute that feature).

**Comment by rpwoodbu** [comment]
In light of learning that there's an SSH agent implementation for Chrome, I am inclined not to build any more functionality into Mosh for Chrome's internal SSH key management. I think I'll keep what we have, just so you don't _have_ to use an external agent for simple usage (and to avoid breaking existing users).

Closing this in favor of Issue #78.

**Comment by oskar456** [comment]
Well, this doesn't really solve the issue with SSH certificates, as there is no way how to load SSH certificate to the Agent app either. But I understand that now it is a someone else's problem, so let's [report it there](https://github.com/google/chrome-ssh-agent/issues/5)! ;)
