### ISSUE TITLE
Pressing escape in mosh configuration text entry resets to default

### ISSUE THREAD

**Issue by gordallott** [rpwoodbu/mosh-chrome#164]
pressing esc in a mosh configuration box resets the text entry to default. Personally i have a bad habit of hitting esc when entering text because I use vim a lot, but this also means i just lost my large custom colour theme as you can not ctrl-z back to how things were 

if this is intentional I might suggest a different key for resetting to default to save some frustration for anyone like me who now has to rebuild their config because they use vim and have no control over their fingers apparently

**Comment by rpwoodbu** [comment]
This is intentional, and is brought over from hterm, the underlying terminal emulator (same as the Secure Shell app). I'm disinclined to go out of my way to try to work around that. Perhaps you could bring it up with the Secure Shell / hterm folks.

One mitigation would be if we provided a way to save/restore profiles, similar to how Secure Shell can. Someone also recently requested the ability to store multiple profiles, which is a related feature.

All that said, as a fellow vim user, I sympathize. :wq
