### ISSUE TITLE
compiling mosh with emscripten to native js?

### ISSUE THREAD

**Issue by gnadelwartz** [rpwoodbu/mosh-chrome#166]
i tiried to cross compile mosh with emscripten, but had many issues with the build scripts of mosh and mosh dependencys. 

do you think itspossible to use your build system also for mosh with emscripten? a problem may that some of the needed library'shas to build also.

my basic idea was to compile mosh-client together with chromes js terminal to run in any asm.js capable browser

**Comment by rpwoodbu** [comment]
Sorry I didn't respond earlier. Missed this one in the mix.

It is definitely possible to get the build system to use different things. It's particularly well-suited to multiple target architectures. You'd need to become very familiar with Bazel, though, to undertake this.

However, this will still not be a simple task. Your main issue will not be getting it to build with emscripten or any other toolchain. The issue will be that Mosh for Chrome is built on the Pepper API, which is Chrome-specific AIUI. Getting this to work in another browser would be a significant development effort. That said, a lot of the underlying facilities are abstracted so that another API could be targeted, but I'm not sure it is worth the effort.

And even if you did all that work, there'd have to be an API in the browser that allows communicating over UDP sockets, which is hard even inside of Chrome (only available to Packaged Apps last I checked, making this unavailable to all but Chrome OS soon).

And honestly, if we were to go down this route, I think the path to take would be [WebAssembly](https://blog.chromium.org/2017/05/goodbye-pnacl-hello-webassembly.html), which is replacing PNaCl. But they're not removing PNaCl support from Chrome Apps (AFAIK), and there's the API issue, so it's merely academic.

Thanks for the interest, though. As you've already gone through the effort of getting Mosh for Chrome to build, let me know if there are other issues you'd be interested in helping out with.

**Comment by vapier** [comment]
emscripten targets webasm, so that shouldn't be an issue

the ppapi layer isn't super bothersome, although switching the messaging model would require a bit of work

i think the biggest issue would be the (P)NaCl runtime.  if you're actually building using PNaCl (hard to tell as the extension ships .nexe ... but maybe the build process just does like Secure Shell and translate the pexe to nexe at build time), then the toolchain provides newlib and some raw networking support. 
 webasm only offers what the web platform does and that's [websockets](https://en.wikipedia.org/wiki/WebSocket) which is basically HTTP over TCP.

it should be feasible to get the runtime libs to use [Chrome App Sockets](https://developer.chrome.com/apps/socket) instead, but i don't think that'll be trivial to pull off :/.  and as you said, it only works for Chrome Apps.

**Comment by rpwoodbu** [comment]
FTR: It builds using the PNaCl toolchain (and newlib). I used to ship a pexe, but later started translating to NaCl (i.e. nexe) at build time to work around a non-deterministic bug in the translator shipped with Chrome OS for ARM that caused the app to crash on startup. AFAIK that bug still exists. The best answer I ever got from the PNaCl folks was "just ship a nexe". But I do have to test it carefully on ARM before I ship, and if it doesn't work, rebuild until it does. 😮 

Yes, there is some networking support in the toolchain and libraries (that wasn't there when I began this project), but there's no getting around needing UDP. And I think one of @gnadelwartz's goals was to get this to work on other browsers, which makes this even more improbable.

**Comment by vapier** [comment]
yeah, unfortunately "just use webasm to make it portable" glosses over deficiencies in the web platform.  the only thing we can get today is a websocket (HTTP over TCP).  until something goes through the w3c and is picked up by browsers, there's not a lot we can do about it.  like the [TCP and UDP Socket API](https://www.w3.org/TR/tcp-udp-sockets/) which, afaict, is stalled.

Mozilla has been trying to standardize a lot of the Chrome Extensions JS APIs under the [Browser Extensions project](https://developer.mozilla.org/en-US/Add-ons/WebExtensions), but the Chrome App Sockets API is missing, most likely for the same reasons -- security is a nightmare.

and no, WebRTC is not a solution here ;).

**Comment by gnadelwartz** [comment]
thank you for responding. my goal was to get it compiled with emscripten, but it as you both explained the real problem is the missing TCP support in other browsers. may be it can be done with websocket proxy but then its no more pure mosh 🤔 and ssh

extending mosh to support websocket will not much better, because ssh is not websocket aware.

**Comment by gnadelwartz** [comment]
I use mosh because of its feature to magically reconnect after network change or network outage.
But not because it uses a superior stateless protocol.

After some thinking about it, the ability to surive a client side IP Adress change should be a feature of the network stack in general today ...

**Comment by rpwoodbu** [comment]
Yes, it really should be part of the network stack. See IPv6 Mobility, and then shed a tear knowing it'll never catch on.
