### ISSUE TITLE
Provide a way to set ssh client config, especially: UseKeychain yes

### ISSUE THREAD

**Issue by javabrett** [rpwoodbu/mosh-chrome#173]
This would be very handy on Mac OS/X, where ssh keys can be stored securely in keychain.

**Comment by rpwoodbu** [comment]
This is unlikely to be feasible, because of the limitations of a Chrome App. I seriously doubt there's any way to get to the OS-level keychain from within the browser, except to use [Native Messaging](https://developer.chrome.com/apps/nativeMessaging), which requires the app to be installed administratively (i.e., not via the Chrome Web Store). There is already support for an SSH agent app (currently only [this one](https://developer.chrome.com/apps/nativeMessaging)), so if someone creates one which talks to the OS-level keychain and follows the same protocol, I could wire it in.

**Comment by vapier** [comment]
Native Messaging is the only way Chrome Apps can talk to native system services (unless those services expose themselves over the network in which case you could do it via sockets or something).

i think you copied & pasted the wrong link for the SSH agent app ... it's the same as the first to native messaging :).
