### ISSUE TITLE
osc52 support for hterm paste to clipboard

### ISSUE THREAD

**Issue by shirro** [rpwoodbu/mosh-chrome#40]
hterm supports osc52 to write from the term to the system clipboard. There are examples of a shell command and vim plugin in libapps/hterm/etc. I have found this works well with Chrome Secure Shell packaged app but when I use mosh, either the packaged app or start mosh over Secure Shell the osc sequence doesn't appear to get through the mosh terminal emulation.

This is probably an upstream issue for mosh. I added a comment at https://github.com/keithw/mosh/issues/382#issuecomment-36415144 but I don't know if it is something that would be fixed upstream. It might be an idea to patch mosh for mosh-chrome because this limits mosh-chrome compared with the Secure Shell app that sets expectations on Chrome. I have looked at the mosh terminal emulation and unfortunately c++ isn't my thing. It looks like they capture OSC sequences and use them for set title and possibly discard the rest but I am not sure how to fix it.

btw tmux also eats osc52 which limits usefullness until I can find a patch for that as well. if testing make sure you aren't running tmux.

**Comment by rpwoodbu** [comment]
At long last, there has been an upstream mosh release, which was brought in by SHA 89ac2b2b8f4809335ca1a1700902d6142f55080e. This should add the mouse support you (@shirro) mentioned. I do not know if it adds the osc52 thing. Let me know if it does, and I can close this out.

**Comment by sunaku** [comment]
@rpwoodbu Thanks! Under initial tests, the new mosh 1.2.5 seems to have fixed OSC-52.  :+1: 

I need to test this on other machines though. I'll reply in (hopefully) a few days with an answer.

**Comment by cgull** [comment]
That's interesting.  We definitely did not add support for OSC-52 in mosh.

It's a non-trivial feature request; it's another variation of the "but I want this reliable byte stream" problem.

**Comment by sunaku** [comment]
@cgull you're right :disappointed:, I finally got to test mosh 1.2.5 on a remote server and OSC-52 doesn't work.  :sweat: What happened in my initial (localhost) test was that [my yank script](https://sunaku.github.io/tmux-yank-osc52.html) _also_ used X11 to copy text into my system clipboard, as a fallback, creating the illusion that mosh was actually passing OSC-52 through. :sweat_smile:

**Comment by rpwoodbu** [comment]
Realizing from @cgull's comment that this requires a non-trivial enhancement to the upstream mosh which isn't likely coming anytime soon, I'm going to close this for now. Please ping this when/if this becomes available upstream, and I'll reopen.

**Comment by acornejo** [comment]
I have implemented this in pull request
https://github.com/mobile-shell/mosh/pull/899

I am a bit weary though, since I see there are multiple PR's on that project, some of them over a year old that have not received a single comment from the mantainers.

**Comment by rpwoodbu** [comment]
I'll gladly reopen this (if needed) once your PR is in an official upstream Mosh release.

It isn't terribly difficult to build Mosh for Chrome, nor build it from your GitHub fork which has your fixes, so you could get this in for yourself sooner. There's some documentation on building Mosh for Chrome in the GitHub wiki.

**Comment by acornejo** [comment]
Sounds good. Hopefully one of the mosh maintainers can take a look over the patch and send me some feedback so that it eventually gets merged.

Perhaps @cgull would be interested in taking a look, since I see he commented on this bug as well.
The patch is simple enough, I piggy backed into the existing OSC infrastructure that handled terminal title changes to handle clipboard changes as well, so I am hoping it wont be too controversial.

Regarding building+running my own fork... when I was younger I enjoyed running my forked versions of everything (including obscure kernel patches). These days I am too old/lazy/busy to keep up with that. In fact this is part of the reason I am giving chrome os a try (coming from linux), so having to use it with customized extensions that I maintain kind of defeats the point.

Of course, if it turns out that its impossible for me to get this feature without building my own fork, I will read up on the wiki and revisit this decision.

**Comment by acornejo** [comment]
https://github.com/mobile-shell/mosh/pull/899 got merged.

Could we get a new mosh-chrome release?

**Comment by rpwoodbu** [comment]
@acornejo Glad you got your PR in! However, I stick with the actual released versions of the upstream Mosh code, so we'll need to wait until they do another release. They _just_ did one (and I haven't quite gotten that out the door yet, still only in the dev track), so it may be a little bit.
