### ISSUE TITLE
Alt-tab on full screen

### ISSUE THREAD

**Issue by whodidthis** [rpwoodbu/mosh-chrome#69]
Would it be possible to make alt tabbing work when using mosh-chrome full screen?

**Comment by rpwoodbu** [comment]
I assume you want to be able to switch windows when in full-screen mode. This is entirely platform-specific. I doubt there's anything I can do to change the Alt-Tab behavior from within the app. I recommend you check how your platform behaves in general, and see if there's anything within the platform you can adjust. I might also recommend simply maximizing the window instead of going full-screen.

**Comment by whodidthis** [comment]
Whoops, sorry for reporting this.

It's an hterm issue anyways https://code.google.com/p/chromium/issues/detail?id=398905

**Comment by rpwoodbu** [comment]
Ah, thanks for the link. If this is indeed an hterm issue, feel free to ping this bug once it is fixed upstream so that I know to do a new build with a new hterm.
