### ISSUE TITLE
SSH agent forwarding

### ISSUE THREAD

**Issue by soichih** [rpwoodbu/mosh-chrome#70]
Is there anyway to implement SSH agent forwarding; preferably reusing Pageant as the key store.. 

I saw mosh itself hasn't implemented the agent forwarding feature, so maybe that needs to happen first, but I wanted to request this feature since I will be using mosh-chrome to access my mosh/ssh server.

**Comment by rpwoodbu** [comment]
I'd like this myself, but as you mention, this isn't available in the upstream mosh code. There may have been some work upstream toward supporting port forwarding (which would make this possible), but I haven't looked in a while. In any case, I'm trying to avoid using any new upstream features until a new official mosh release happens (it's pushing two years since the last one).

Although this isn't agent forwarding, one thing I've considered is implementing some sort of quasi-agent that would at least cache the unencrypted version of your ssh key for the duration of your Chrome session so you don't have to enter your passphrase for new connections. Unfortunately, I don't think I could use an existing agent (e.g., ssh-agent, Pageant) due to Chrome sandboxing. Even if I could, it'd likely require a very broad, scary app permission. And for this to work on Chrome OS (the primary use case), there'd still have to be an agent implemented in the app (or in another cooperating Chrome app).

To mitigate the lack of agent forwarding, I just run an agent on the remote system. Of course, that means copying my key material there, but I mostly mosh to trusted "bastion" machines.
