### ISSUE TITLE
Improve error message when using unsupported ssh key type

### ISSUE THREAD

**Issue by haarts** [rpwoodbu/mosh-chrome#71]
I've tried adding a ed25519 key. Adding seems to work, the bahaviour is the same as when adding a regular RSA key. However, when connecting, it asks me my password. But it doesn't accept it (I'm sure I've typed it right). The wiki mentions the key needing to be in PEM format. I _believe_ my ed25519 key is.

The format in `.ssh/id_ed25519` is:
```
-----BEGIN OPENSSH PRIVATE KEY-----
Grabled text
-----END OPENSSH PRIVATE KEY----- 
```
It _does_ miss some headers I see with my RSA key. Might that be the issue?

**Comment by rpwoodbu** [comment]
Mosh for Chrome depends on [libssh](http://www.libssh.org/), and I'm not sure it supports the key type you're trying to use. A better error message is likely in order, so I'll keep this bug open to improve that.

**Comment by rpwoodbu** [comment]
Unfortunately, [libssh](http://www.libssh.org/) doesn't provide enough insight into why the key didn't load. The `ssh_pki_import_privkey_base64()` call just returns an `SSH_ERROR` or an `SSH_OK`. So Mosh for Chrome can't know if it didn't load because the format is wrong, the key type is unsupported, or the passphrase was wrong.

If this is a major issue for you, please take it up with the libssh folks to improve the API. You can reopen this bug once libssh has done a release with the functionality required, and I'll see about using the improved API to make the error reporting more precies. In the meantime, I'm improving the error message to be more explanatory, at the least.
