### ISSUE TITLE
Make "Remote command" field work more like mosh command does

### ISSUE THREAD

**Issue by gsf** [rpwoodbu/mosh-chrome#82]
With the command-line mosh I'm used to attaching to tmux on connect:

```
$ mosh gsf.io tmux a
```

With a `tmux a`, or really any command including `bash`, in the "Remote command" box, however, mosh-chrome hangs after the following:

```
Loading NaCl module (takes a while the first time after an update).

Loaded.
Fingerprint of remote ssh host (MD5):
  94:33:1d:68:77:10:76:8c:02:7c:46:3e:60:1b:f4:94
Authentication types supported by server:
 - Password
 - Public Key
Trying authentication type Public Key
```

Authentication and login work fine when "Remote command" is left blank. Am I using it wrong?

**Comment by rpwoodbu** [comment]
This is a usability issue that even hit me once, and I wrote the stupid thing! ;)

This was just a hack I threw in there because it was easy to do, and solved a problem I was having. I didn't consider feature parity with the `mosh` command.

That field is actually the whole remote command for the other end, including the `mosh-server` part (which is ordinarily covered by the `--server` option). This makes it really hard to use for the typical case such as yours, because `mosh-server` really needs a few command-line flags to give the best experience.

I'll take this issue as an opportunity to make this work more like it does in the `mosh` command.

**Comment by gsf** [comment]
Sounds like a good direction to take things in. Thanks.

**Comment by gsf** [comment]
That works! Thanks.
