### ISSUE TITLE
setting MOSH_ESCAPE_KEY appears to do nothing

### ISSUE THREAD

**Issue by hdp** [rpwoodbu/mosh-chrome#83]
After setting what I think this the correct hterm pref (mosh_client_.io.terminal_.prefs_.set('environment', {TERM: 'xterm-256color', MOSH_ESCAPE_KEY: '~'})), I still have C-^ as the escape key.  This environment variable was changed in mosh in May 2013 (https://github.com/keithw/mosh/commit/f960a8bcf56294ca7aafe3c14fc8c8c4c3941535), so I expected it to work in mosh-chrome.

Am I holding it wrong?

**Comment by keithw** [comment]
That feature is only in Git. It hasn't been documented yet (which we will
need to do before we can release a Mosh with it). Happy to take a pull
request to keithw/mosh that adds it to the man page.

**Comment by rpwoodbu** [comment]
Furthermore, Mosh for Chrome doesn't make use of this "environment" setting in `hterm` (this is the first I've heard of it). The Native Client environment cleans out the environment, so some effort would have to be taken to reconstruct it.

FYI: There's a pull request outstanding which adds a page for setting these kinds of things. They're all `hterm` settings at the moment, but once that's in, I may expand it to include settings such as these. Of course, since the upstream mosh hasn't cut a release with this (as @keithw points out), we'll have to wait.

Feel free to ping this bug or open a new one once this is in an upstream mosh release, and we can see about exposing this option.
