### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by zombiezen** [rpwoodbu/mosh-chrome#87]
keithw/mosh#81 mentions that there is an experimental -6 flag that can be used.. it would be great if IPv6 support was available in this app.

**Comment by rpwoodbu** [comment]
IPv6 support hasn't been released in the upstream `mosh`. Once it has, I probably won't sleep until I've made that work with Mosh for Chrome (I've even put TODOs in the right spots to add IPv6). But it is important to preserve the stability of Mosh for Chrome, which means it cannot depend on unreleased code.

**Comment by rpwoodbu** [comment]
That said, if someone wants to fork this project and create a version that tracks the upstream `mosh` head of development, more power to them. I don't have the cycles for this, though.

**Comment by keithw** [comment]
We (Mosh) would obviously prefer that you not do that, but of course anybody can if they want to. We've found IPv6 a bit frustrating to do in a cross-platform way (probably self-inflicted from our Perl and from our slowness in doing another release). @rpwoodbu , what is your opinion on a release of Mosh that would only enable IPv6 with a -6 flag (and if so, the session would be IPv6-only and would not be able to roam to IPv4-only networks or IPv4 interfaces of the server) -- is this valuable? Or how much more valuable is doing this automatically?

**Comment by rpwoodbu** [comment]
@keithw I've thought about this some. So long as it is behind a flag, it should Do No Harm, but would have marginal value for most. That said, I'd absolutely use it, as I have IPv6 in most places I use a computer, and find myself occasionally frustrated that my mosh sessions to some machines are busted until I get back to the internal network where I connected with an RFC1918 address.

I think cross-protocol roaming would be a neat feature, but IPv6-only networks are so rare that it would have an even more marginal value. But I don't imagine it'd be that hard to implement, especially if you didn't try at all to favor one protocol over the other, but just use whatever most recently worked. Flapping could be an issue, I suppose... I'd need to think about it more.

On a more general note, it'd be nice to see a mosh release at some point soon, since it has been a long while. There's also a pile of pull requests (including one of mine) that deserve some attention. ;)

**Comment by keithw** [comment]
Thanks for this feedback! And re: mosh release, we are trying to get a mahimahi release out in the next week or so, and then I will have some cycles to get back to mosh. Thank you for your patience!

**Comment by zombiezen** [comment]
Awesome! This sounds great.

**Comment by ardje** [comment]
Hello keithw,
I can assure you that IPv6 networks are pretty common in my world. I do not have to roam between ipv6 and ipv4. Most/all of the machines I manage have ipv6 native or by a tunnel. The most important feature about mosh vs ssh is that I can see what I type. With rtt's going up to 1s you know what I mean ;-). And that's probably why you wrote mosh.
The most important feature about IPv6 is that I do not have to tunnel-in-tunnel-in-tunnel, and that I do not have to worry about IP name space clashing when creating tunnels.
Of course a lot more features will make it even better, but those are exactly that: features. But basic ipv6 (not roaming between v4 and v6) is for me at this moment a basic necessity.
