### ISSUE TITLE
Mosh server command in the extension

### ISSUE THREAD

**Issue by KaptenJansson** [rpwoodbu/mosh-chrome#99]
I'm wondering what commands I can actually use in the Mosh server command field in the Mosh Chrome extension. `-p 60001` does not work (I want to tell the server which port to use but I guess I have to do that when starting mosh on the server?)

**Comment by KaptenJansson** [comment]
Ow I see, I have to enter `mosh -p 60001` but then what? Hostname of the server does not work?

**Comment by KaptenJansson** [comment]
To give more context:

I want only to open up 5 ports to the internet. I want to be able to connect locally as well as via the internet. When I connect from the internet I want to be able to either tell the mosh extension explicitly or have it do it automatically which port mosh it should use.

Currently I see several stale sessions running on my linux box consuming ports resulting in Mosh using 60001-60007 (I've not yet limited the port range). When will mosh let me reuse the ports? I mean, I have 7 mosh instances, it seems that it sometimes creates a new instances when I connect from the same 3 clients using the Chrome extension.

What makes mosh create a new server instance rather than reusing an existing one?

**Comment by rpwoodbu** [comment]
I realized there was no documentation on how to use the _Mosh server command_ field. I have [rectified that](https://github.com/rpwoodbu/mosh-chrome/wiki/Documentation).

This next bit is about mosh generally, not Mosh for Chrome specifically, but it applies just the same.

When you create a new mosh session, a `mosh-server` is run on the remote machine. This process will persist until it is told to exit, or the command that it ran on startup (usually your shell) exits. If the connection between the client and the server is broken. `mosh-server` will wait forever for it to come back. This is by design.

The disadvantage of this strategy is that you can "leak" `mosh-server` processes. If the client is forcibly  killed, for instance, the `mosh-server` has no way to know that, and there is no way to connect to it again. This is what happens when you hit the "X" on the Mosh for Chrome window, or when the browser crashes, or when your computer spontaneously reboots, etc.

The port number is consumed for the duration of any `mosh-server` process. Creating a new session will simply create a new process with a new port number, regardless of which computer you connect from. It never reuses old instances of `mosh-server`. The only way to "clean up" is to kill any "leaked" `mosh-server` processes. Mosh attempts to help you with this by listing unconnected `mosh-server` processes when you start a new one.

This is a common problem. I have my own workaround for this. I have created a script that I call `mosh-named-server`, and I use a different name for each machine from which I connect. If a `mosh-server` with the same name exists when I connect, it just gets killed. This is OK, since I always run `tmux`, so I never lose my shell session (highly recommended anyway, since you can't recover a "stranded" `mosh-server` session). This technique helps mitigate "leaking". If there is demand for this shell script, I will share it; it does require tweaking the _Mosh server command_ field to make use of it.

So to answer your question directly: I would first simply recommend keeping things tidy, and that should prevent you from having to specify port numbers. If you do find you want to specify a port number, see the documentation linked above for how to use the _Mosh server command_ field, and you'll see how you can add the `-p 60041` bit to it. NB: If you already have a `mosh-server` using that port, starting a new one with that option will simply fail.

**Comment by KaptenJansson** [comment]
Thank you for the thorough explanation. Then it makes sense, and yes I use tmux as well. If you could share the script it would be great, as I see that as a potential problem (at least for my current server setup).

**Comment by computersarecool** [comment]
@rpwoodbu I would be curious in your `mosh-named-server` script.  Is it available anywhere?
